### ISSUE TITLE
Design of lazy evaluation for some properties

### ISSUE THREAD

**Issue by garawalid** [databricks/spark-pandas#118]
#### The idea behind this issue is to discuss the design of lazy evaluation for properties. 

I think we need this behavior especially with a property like [values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html).  We will load all the data in `values` when we create a new DataFrame and this becomes heavy when the data is huge. 

I found a good trick [here](https://stackoverflow.com/questions/20535342/lazy-evaluation-in-python) and I think it can be useful. We just need to override `__get__()`. 

Any idea related to the topic and we can use it in Koalas?

For instance, we can solve `values` by replacing it by `to_numpy()`. 
Pandas documentation suggests.
```
Warning: We recommend using DataFrame.to_numpy() instead.
 ```

**Comment by rxin** [comment]
Does Python automatically materialize all the properties when the class is created? If yes, I definitely agree we shouldn't create "values" ...

**Comment by garawalid** [comment]
Yes, it does. 
Here is an example. I implemented `values` as property in `_Frame` class. 
```python 
    @property
    def values(self):
        return self.toPandas().values
```
Running this code will show us that the property `values` contains already the data as numpy array.
 ```python 
df = pd.DataFrame({'a': [4, 2, 3, 4, 8, 6],
                    'b': [1, 2, 9, 4, 2, 4],
                    'c': ["one", "three", "six", "seven", "one", "5"]},
                    index=[10, 20, 30, 40, 50, 60])

ddf = self.spark.from_pandas(df)
```

A screen capture from the debugger stopped after creating `ddf`

![values](https://user-images.githubusercontent.com/20029252/56464049-17d2e780-63e1-11e9-9add-2e62c7662fd2.png)

**Comment by AbdealiJK** [comment]
A debugging tool would typically get all attributes in dir() and request for every attribute. Checking it in a debugger may not be an accurate test

**Comment by garawalid** [comment]
@AbdealiJK 
Thanks! You are right, it's not an accurate test. 
I tried it with this simple test, and the message doesn't appear when we create the dataframe. 

```python
@property
def values(self):
    print("executed !")
    return self.toPandas().values
```

**Comment by garawalid** [comment]
So, we can say that properties are lazy by default!

**Comment by rxin** [comment]
Thanks. Looks like we are safe here. I'm going to close this ticket. Feel free to reopen if there is an issue in the future.
