### ISSUE TITLE
Documentation setup

### ISSUE THREAD

**Issue by AbdealiJK** [databricks/spark-pandas#40]
I think it would be awesome if some sort of readthedocs like documentation could be started.

I have begun exploring some stuff and rather than storing it all in my head could write it out so that it becomes a reference for other+me.

**Comment by HyukjinKwon** [comment]
I am closing this as a dup of https://github.com/databricks/spark-pandas/issues/42

**Comment by HyukjinKwon** [comment]
Can we close this as a dup of #87?
