### ISSUE TITLE
Publish the package documentation

### ISSUE THREAD

**Issue by thunterdb** [databricks/spark-pandas#42]
We should publish documentation to explain the changes that this package brings:
 - list of status of all the methods: it can be a markdown file, for example, that exports the content of the spreadsheet
 - full python doc of the modified pyspark.DataFrame and pyspark.Column to provide a reference to what is implemented
 - (if possible) embed a quick tutorial once it is written

**Comment by AbdealiJK** [comment]
Are you thinking that would be in readthedocs or so ?
Possibly related: https://github.com/databricks/spark-pandas/issues/40

**Comment by thunterdb** [comment]
Yes, I am thinking about readthedocs for the time being.

**Comment by gatorsmile** [comment]
@HyukjinKwon

**Comment by HyukjinKwon** [comment]
We should take a look for sphinx first and see if it generates the doc properly. Let me take a look.

**Comment by HyukjinKwon** [comment]
Can we close this as a dup of #87?

**Comment by rxin** [comment]
Yes- this is a dup.
