### ISSUE TITLE
use https://hackmd.io/instead of googledoc

### ISSUE THREAD

**Issue by obar1** [databricks/spark-pandas#60]
copy and paste the content in  
**google doc** 
in # What is available

with one in   https://hackmd.io/auth/github
and update the radme

**Comment by thunterdb** [comment]
@obar1 can you elaborate? Google doc provide a stable and documented API in python and REST, is very robust and has a lot of features to do pivoting, etc. We can use that to present the high priority elements to be worked on.

**Comment by rxin** [comment]
Thanks for the feedback. I think this ticket will be subsumed by https://github.com/databricks/spark-pandas/issues/77 because we will remove the Google Docs and use our source code as the source of truth for roadmap & contributions.

Closing now.
