### ISSUE TITLE
Billion dollar question: Koala or Koalas?

### ISSUE THREAD

**Issue by rxin** [databricks/spark-pandas#85]
@GregOwen suggested using Koalas because it is more of a nod to "Pandas".

**Comment by gatorsmile** [comment]
+1

**Comment by ileshko** [comment]
+1

**Comment by gatorsmile** [comment]
> https://www.dlr.de/sc/Portaldata/15/Resources/dokumente/pyhpc2011/submissions/pyhpc2011_submission_9.pdf

lower case? `koalas`

**Comment by thunterdb** [comment]
Koalas with a capital K sounds good

**Comment by rxin** [comment]
Alright it's been decided. We are renaming the project to Koalas!

**Comment by mateiz** [comment]
I actually think Koala is easier to remember, but up to you!
