### ISSUE TITLE
Should we simplify stub code?

### ISSUE THREAD

**Issue by rxin** [databricks/spark-pandas#91]
Right now they look like:

```
    def add(self, other, axis='columns', level=None, fill_value=None):
        """A stub for the equivalent method to `pd.DataFrame.add()`.
        The method `pd.DataFrame.add()` is not implemented yet.
        """
        raise PandasNotImplementedError(class_name='pd.DataFrame', method_name='add')
```

Should we simplify it to something like

```
def add(**kwargs):
  unsupported_function()
```

or

```
add = unsupported_function()
```

or even

```
unsupported_function('add')
```

Reason I think we should simplify:

1. I don't see a strong need to show all the arguments, in addition to the function name. (Correct me if I'm wrong).
2. Perception wise, it'd be better to have a shorter missing file than a very long file.

**Comment by rxin** [comment]
@ueshin @thunterdb thoughts on this?

**Comment by ueshin** [comment]
1) I'd prefer to preserve the arguments, but not a strong opinion. As for the function name, we might want to show the original class name and the function name in the error message.

```py
add = unsupported_function('pd.DataFrame', 'add')
```

2) I definitely agree with you.

**Comment by rxin** [comment]
@ueshin can we infer the funciotn name and class name from the callstack?

**Comment by ueshin** [comment]
If we do like `add = unsupported_function`, then seems like the callstack only shows `unsupported_function`.

```py
>>> import inspect
>>> import traceback
>>>
>>> def unsupported_function(*args, **kwargs):
...   print('args: {}, kwargs: {}'.format(args, kwargs))
...   print(inspect.stack())
...   traceback.print_stack()
...
>>> class DF(object):
...   add = unsupported_function
...
>>> DF().add()
args: (<__main__.DF object at 0x108640be0>,), kwargs: {}
[FrameInfo(frame=<frame object at 0x108625048>, filename='<stdin>', lineno=3, function='unsupported_function', code_context=None, index=None), FrameInfo(frame=<frame object at 0x10858ba08>, filename='<stdin>', lineno=1, function='<module>', code_context=None, index=None)]
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in unsupported_function
```

**Comment by rxin** [comment]
Ah ok. That sucks. Then we should definitely add classname and function name to the parameter list. Maybe for each class we can have a wrapper to not have to specify the class name every time.
